version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres-job
    ports:
      - "5206:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: job_application_db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./Backend
    container_name: backend-job
    ports:
      - "3206:3206"
    depends_on:
      - postgres
    environment:
      NODE_ENV: development

  employee-job:
    build: ./Employee-job
    container_name: Employee-job
    ports:
      - "8012:80"
    depends_on:
      - backend

  hr-job:
    build: ./HR-job
    container_name: HR-job
    ports:
      - "8013:80"
    depends_on:
      - backend

volumes:
  pgdata:

